### ISSUE TITLE
implement deployment update on new image for application

### ISSUE THREAD

**Issue by konstan** [nuvla/api-server#260]
Related to https://github.com/nuvla/job-engine/issues/64

**Comment by konstan** [comment]
In the multi-service application case with the same `image:tag` for different services

```
services:
  s1:
    image: image:1.2.3
  s2:
    image: image:1.2.3  
```

should we:

A. generate per service notifications with the corresponding per service update actions (only single action can be running at a time; queue of requested actions is needed).
```
Notification 1: app X new image image:1.2.4 for service s1. 
Action 1: update s1 on app X with image:1.2.4.

Notification 2: app X new image image:1.2.4 for service s2.
Action 2: update s2 on app X with image:1.2.4.
```
The order of the actioned notifications defines the execution order of the actions.

B. generate a single notification on all the application services for the new image with only one update action.
```
Notification: app X new image image:1.2.4 for services s1, s2.
Action: update s1, s2 on app X with image:1.2.4.
```

C. B. with an ability to chose `ALL` or `one-by-one (and order)`.
```
Notification: app X new image image:1.2.4 for services s1, s2.
Action Option "ALL": update s1, s2 on app X with image:1.2.4. (B. default)
Action Option "one-by-one": (A. in user selected order)
  Action 1: update s2 on app X with image:1.2.4.
  Action 2: update s1 on app X with image:1.2.4. 
```

Nuvla examples. 

DB. With minor/patch updates `elasticsearch:7.y,z`. Options: C. `one-by-one` with order db-2, db-1; A. order db-2, db-1.

```
services:
  db-1:
    image: elasticsearch:7.0.0
  db-2:
    image: elasticsearch:7.0.0
```

Jobs. Although, A. is possible, B. or C. `ALL` would be preferable.

```
services:
  jobd-jobs-cleanup:
    image: nuvla/job:2.3.8
  jobd-deployment-state:
    image: nuvla/job:2.3.8
  jobd-comp-image-state:
    image: nuvla/job:2.3.8
  jobd-srvc-image-state:
    image: nuvla/job:2.3.8
  # more coming
```
