### ISSUE TITLE
generalize schema for NB metrics

### ISSUE THREAD

**Issue by konstan** [nuvla/api-server#435]
Here is the proposal to generalize the NB telemetry schema to turn it into a carrier of any kind of metrics.

Below is the current representation of the resource metrics for cpu, ram, disks, and network interfaces.

```
"resources" : {
    "cpu" : {
      "topic" : "cpu",
      "raw-sample" : "{\"capacity\": 4, \"load\": 0.91}",
      "capacity" : 4,
      "load" : 0.91
    },
    "ram" : {
      "topic" : "ram",
      "raw-sample" : "{\"capacity\": 926, \"used\": 316}",
      "capacity" : 926,
      "used" : 316
    },
    "disks" : [ {
      "device" : "mmcblk0p2",
      "capacity" : 59,
      "used" : 16,
      "topic" : "disks",
      "raw-sample" : "{\"device\": \"mmcblk0p2\", \"capacity\": 59, \"used\": 16}"
    } ],
    "net-stats" : [ {
      "interface" : "veth9eaefa1",
      "bytes-transmitted" : 63323,
      "bytes-received" : 1183
    }, {
      "interface" : "veth79f86fb",
      "bytes-transmitted" : 142819,
      "bytes-received" : 688
    }, ... 
```

I suggest turning this into a list of generically defined metric representation maps. We also need metric collection an event timestamp. The telemetry "packaging" timestamp (`current-time`) on the resource document itself is not enough.

```
metrics:
   - kind: kind of the metric {cpu, ram, disks, iface, etc}
     name: name of the metric {"cpu load", "mem free", "disk hdd01", "interface veth0", etc}
     metric: what is measured {load, used, tx, rx, etc}
     value: 123.45
     unit: MiB, GiB, bytes, etc
     capacity: (optional) for capacity defined resources like cpu, ram, disk where the overall capacity is known (handy for computing %)
     ts: metric collection event timestamp in millis
   - kind: ...
```

This is an example of the cpu metric

```
    {
      "kind": "cpu",
      "name": "cpu load5",
      "metric": "load5",
      "value": 0.1,
      "capacity": 4,
      "ts": 1610608233355
    }
```

Here is an example of the list with a number of metrics

```
{
  "id": "nuvlabox-status/123",
  "metrics": [
    {
      "kind": "cpu",
      "name": "cpu",
      "metric": "load",
      "value": 0.1,
      "capacity": 4,
      "ts": 1610608233355
    },
    {
      "kind": "ram",
      "name": "ram",
      "metric": "used",
      "value": 1234,
      "capacity": 4096,
      "unit": "MiB",
      "ts": 1610608233356
    },
    {
      "kind": "disk",
      "name": "mmcblk0p2",
      "metric": "used",
      "value": 25000,
      "capacity": 500000,
      "unit": "MiB",
      "ts": 1610608233357
    },
    {
      "kind": "interface",
      "name": "veth9eaefa1",
      "metric": "tx",
      "value": 2345123,
      "unit": "bytes",
      "ts": 1610608233358
    },
    {
      "kind": "interface",
      "name": "veth9eaefa1",
      "metric": "rx",
      "value": 123090,
      "unit": "bytes",
      "ts": 1610608233359
    }
  ]
}
```

This allows delivering metrics which sampling rate is higher than the telemetry update period. This assumes the metrics collector has a buffer. E.g., where for "kind+name+metric" they are unique by "ts".

```
    {
      "kind": "interface",
      "name": "veth9eaefa1",
      "metric": "tx",
      "value": 2345123,
      "unit": "bytes",
      "ts": 1610608233000
    },
    {
      "kind": "interface",
      "name": "veth9eaefa1",
      "metric": "tx",
      "value": 2345145,
      "unit": "bytes",
      "ts": 1610608233101
    },
```

An overall optimization would be turning `value` field into `values` list of `(ts, value)` tuples. On an example of the above

```
    {
      "kind": "interface",
      "name": "veth9eaefa1",
      "metric": "tx",
      "values": [[1610608233101, 2345145], [1610608233000, 2345123]]
      "unit": "bytes"
    }
```
