### ISSUE TITLE
add default-gw to nuvlabox-status

### ISSUE THREAD

**Issue by konstan** [nuvla/api-server#698]
Extend `nuvlabox-status` schema by adding `default-gw` (string) attribute with the value being the current default gateway on the NE. 
Immediate usage: defining notifications on the network traffic via default gateway on NE.

**Comment by konstan** [comment]
After a discussion we agreed on extending `nuvlabox-status` with `network:` root level map. Server side it will be a free map. The structure will be provided by NB agent. This is the provisional structure 

```
network:
   default-gw: eth0
   interfaces:
      eth0:
         ip: 1.2.3.4
         foo: bar
      eth1:
         ip: 2.3.4.5
         foo: baz
   ips:
     swarm: 0.0.0.0
     ...
```

For this ticket, it was agreed that NB agent will provide the default gateway under `network->default-gw`.
